// Generates src/data/joValues.js: f_k(lambda) for k = 0..K of the five Jeffrey-Onishi families at the
// size ratios lambda = a2/a1 offered on the pages (1, 1/2, 2, 1/4, 4).
// The recurrence coefficients do not depend on lambda, so they are computed once (about 3 minutes
// for K = 200) and the polynomials are then evaluated at each ratio.
// Run: node --max-old-space-size=12000 scripts/generate-jo-data.mjs [K]
import { writeFileSync } from "node:fs";
import { joAllPolynomials, hornerAt } from "../src/physics/joRecurrence.js";

const K = Number(process.argv[2] ?? 200);
const LAMBDAS = [1, 0.5, 2, 0.25, 4];
const t0 = Date.now();
const P = joAllPolynomials(K);
const block = LAMBDAS.map((l) => {
  const fams = Object.entries(P).map(([name, rows]) => `    ${name}: [${rows.map((c) => hornerAt(c, l).toPrecision(17)).join(", ")}],`);
  return `  "${l}": {\n${fams.join("\n")}\n  },`;
});
writeFileSync(new URL("../src/data/joValues.js", import.meta.url),
  `// Generated by scripts/generate-jo-data.mjs (K = ${K}). Do not edit by hand.\n` +
  `// f_k(lambda) of the Jeffrey-Onishi (1984) far-field series for XA, YA, YB, XC, YC, at lambda = a2/a1.\n` +
  `export const K = ${K};\nexport const LAMBDAS = ${JSON.stringify(LAMBDAS)};\nexport const F = {\n${block.join("\n")}\n};\n`);
console.log(`K = ${K}: ${((Date.now() - t0) / 1000).toFixed(1)} s`);
