// Generates src/data/joLambda1.js: f_k(1) for k = 0..K of the five Jeffrey-Onishi families
// (equal spheres). Run: node --max-old-space-size=12000 scripts/generate-jo-data.mjs [K]
// K = 200 takes about two minutes.
import { writeFileSync } from "node:fs";
import { joAllValues } from "../src/physics/joRecurrence.js";

const K = Number(process.argv[2] ?? 200);
const t0 = Date.now();
const v = joAllValues(K, 1);
const lines = Object.entries(v).map(([name, arr]) => `  ${name}: [${arr.map((x) => x.toPrecision(17)).join(", ")}],`);
writeFileSync(new URL("../src/data/joLambda1.js", import.meta.url),
  `// Generated by scripts/generate-jo-data.mjs (K = ${K}). Do not edit by hand.\n` +
  `// f_k(lambda = 1) of the Jeffrey-Onishi (1984) far-field series for XA, YA, YB, XC, YC.\n` +
  `export const K = ${K};\nexport const F = {\n${lines.join("\n")}\n};\n`);
console.log(`K = ${K}: ${((Date.now() - t0) / 1000).toFixed(1)} s`);
